/*
 * Window.java
 *
 * Created on __DATE__, __TIME__
 */

package compiler.ui;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;


import compiler.nfa.R2NFA;
import compiler.nfa.io.ReadFile;
import compiler.nfa.util.State;
import compiler.util.MyLinkedList;

/**
 *
 * @author  焦建
 */
public class Window extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form Window */
	public Window() {
		initComponents();
		this.setResizable(false);
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jSeparator1 = new javax.swing.JSeparator();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable3 = new javax.swing.JTable();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextField1.setText("输入正规式以#结束");

		jButton1.setText("检查正规是的正确性");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextArea1.setText(null);
				R2NFA nfa=new R2NFA(file);
				nfa.go();
				for(int i=MyLinkedList.getNFAlist().size()-1;i>=0;i--){
					jTextArea1.append(""+MyLinkedList.getNFAlist().get(i).getFrom()
							+"---"+MyLinkedList.getNFAlist().get(i).getReceive()
							+"---"+MyLinkedList.getNFAlist().get(i).getTo()+'\n');
				}
				jTextField2.setText(""+MyLinkedList.getNFAlist().peekLast().getFrom());
				jTextField3.setText(""+(State.weight-1));
				jButton2.setEnabled(false);
			}
		});


		jScrollPane3.setViewportView(jTable3);

		jButton2.setText("R-NFA");

		jButton3.setText("NFA-DFA");

		jButton4.setText("DFA简化");
		jButton2.setEnabled(false);
		jButton3.setEnabled(false);
		jButton4.setEnabled(false);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setEditable(false);
		jScrollPane1.setViewportView(jTextArea1);

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jTextArea2.setEditable(false);
		jScrollPane2.setViewportView(jTextArea2);

		jTextArea3.setColumns(20);
		jTextArea3.setRows(5);
		jTextArea3.setEditable(false);
		jScrollPane4.setViewportView(jTextArea3);
		jTextField2.setEditable(false);
		jTextField3.setEditable(false);
		jTextField4.setEditable(false);
		jTextField5.setEditable(false);
		jTextField6.setEditable(false);
		jTextField7.setEditable(false);
		
		jLabel1.setText("From--Get--To");

		jLabel2.setText("From--Get--To");

		jLabel3.setText("From--Get--To");

		jLabel4.setText("开始节点：");

		jLabel5.setText("终结节点：");

		jLabel6.setText("开始节点：");

		jLabel7.setText("终结节点：");

		jLabel8.setText("开始节点：");

		jLabel9.setText("终结节点：");

	

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(277, 277,
										277).addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										348,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(30, 30, 30).addComponent(
												jButton1).addGap(55, 55, 55))
						.addComponent(jSeparator1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 791,
								Short.MAX_VALUE)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												23,
																												23,
																												23)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jScrollPane1,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																228,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addGroup(
																																layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.TRAILING,
																																				false)
																																		.addGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				layout
																																						.createSequentialGroup()
																																						.addComponent(
																																								jLabel5)
																																						.addPreferredGap(
																																								javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																						.addComponent(
																																								jTextField3))
																																		.addGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				layout
																																						.createSequentialGroup()
																																						.addComponent(
																																								jLabel4)
																																						.addPreferredGap(
																																								javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																						.addComponent(
																																								jTextField2,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								114,
																																								javax.swing.GroupLayout.PREFERRED_SIZE)
																																						.addPreferredGap(
																																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												49,
																												49,
																												49)
																										.addComponent(
																												jLabel1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												124,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												11,
																												11,
																												11)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																														.addComponent(
																																jButton3)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																						.addComponent(
																																								jLabel7)
																																						.addComponent(
																																								jLabel6))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING,
																																								false)
																																						.addComponent(
																																								jTextField4)
																																						.addComponent(
																																								jTextField5,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								161,
																																								Short.MAX_VALUE))
																																		.addGap(
																																				5,
																																				5,
																																				5))
																														.addComponent(
																																jScrollPane2)))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												50,
																												50,
																												50)
																										.addComponent(
																												jLabel2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												122,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				143,
																				143,
																				143)
																		.addComponent(
																				jButton2)))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jButton4)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																						.addComponent(
																																								jLabel9)
																																						.addComponent(
																																								jLabel8))
																																		.addGap(
																																				18,
																																				18,
																																				18)
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING,
																																								false)
																																						.addComponent(
																																								jTextField7)
																																						.addComponent(
																																								jTextField6,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								131,
																																								Short.MAX_VALUE))))
																										.addContainerGap(
																												115,
																												Short.MAX_VALUE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jScrollPane3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												268,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addContainerGap()))
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addGap(
																								49,
																								49,
																								49)
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								111,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addContainerGap()))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				238,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap()))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(22, 22, 22)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												12,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																0,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel2)
																		.addComponent(
																				jLabel1)
																		.addComponent(
																				jLabel3)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																397,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																397,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																397,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel8))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7)
														.addComponent(
																jTextField7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton2)
														.addComponent(jButton3)
														.addComponent(jButton4))
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	JDialog dialog = null;
	JDialog dialog2 = null;
	String file = "";

	public void unlock() {
		this.setEnabled(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		MyLinkedList.getNFAlist().clear();//清除弧堆栈
		State.clear();//清楚状态堆栈
		ReadFile rf = new ReadFile();
		rf.setFile(jTextField1.getText());
		file = rf.isCorrect();

		
		if (file == null) {
			if (dialog == null) {
				dialog = new JDialog(this, "错误提示", false);

				dialog.setBounds(500, 300, 100, 100);
				dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

				JPanel panel = new JPanel();
				JButton button = new JButton("确定");
				JLabel label = new JLabel("输入的正规式有错误");
				panel.add(label);
				panel.add(button);
				dialog.add(panel);

				button.addActionListener(new ActionListener() {

					@Override
					public void actionPerformed(ActionEvent e) {
						dialog.setVisible(false);
						unlock();
					}

				});
			}
			dialog.setVisible(true);
			jButton2.setEnabled(false);
			this.setEnabled(false);

		} else {
			if(dialog2==null){
			dialog2 = new JDialog(this, "提示", false);

			dialog2.setBounds(500, 300, 100, 100);
			dialog2.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

			JPanel panel = new JPanel();
			JButton button = new JButton("确定");
			JLabel label = new JLabel("正规式正确");
			panel.add(label);
			panel.add(button);
			dialog2.add(panel);

			button.addActionListener(new ActionListener() {

				@Override
				public void actionPerformed(ActionEvent e) {
					dialog2.setVisible(false);
					unlock();
				}

			});}
			dialog2.setVisible(true);
			jButton2.setEnabled(true);
			this.setEnabled(false);

		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Window().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTable jTable3;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	// End of variables declaration//GEN-END:variables

}